/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the QuotePriceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotePriceResponse{}

// QuotePriceResponse struct for QuotePriceResponse
type QuotePriceResponse struct {
	TenantLocator    string            `json:"tenantLocator"`
	QuoteLocator     string            `json:"quoteLocator"`
	AccountLocator   string            `json:"accountLocator"`
	QuoteState       string            `json:"quoteState"`
	ProductName      string            `json:"productName"`
	StartTime        time.Time         `json:"startTime"`
	EndTime          time.Time         `json:"endTime"`
	Duration         float32           `json:"duration"`
	DurationBasis    string            `json:"durationBasis"`
	Items            []Charge          `json:"items"`
	QuoteNumber      string            `json:"quoteNumber"`
	ValidationResult *ValidationResult `json:"validationResult,omitempty"`
}

type _QuotePriceResponse QuotePriceResponse

// NewQuotePriceResponse instantiates a new QuotePriceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotePriceResponse(tenantLocator string, quoteLocator string, accountLocator string, quoteState string, productName string, startTime time.Time, endTime time.Time, duration float32, durationBasis string, items []Charge, quoteNumber string) *QuotePriceResponse {
	this := QuotePriceResponse{}
	this.TenantLocator = tenantLocator
	this.QuoteLocator = quoteLocator
	this.AccountLocator = accountLocator
	this.QuoteState = quoteState
	this.ProductName = productName
	this.StartTime = startTime
	this.EndTime = endTime
	this.Duration = duration
	this.DurationBasis = durationBasis
	this.Items = items
	this.QuoteNumber = quoteNumber
	return &this
}

// NewQuotePriceResponseWithDefaults instantiates a new QuotePriceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotePriceResponseWithDefaults() *QuotePriceResponse {
	this := QuotePriceResponse{}
	return &this
}

// GetTenantLocator returns the TenantLocator field value
func (o *QuotePriceResponse) GetTenantLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantLocator
}

// GetTenantLocatorOk returns a tuple with the TenantLocator field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetTenantLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantLocator, true
}

// SetTenantLocator sets field value
func (o *QuotePriceResponse) SetTenantLocator(v string) {
	o.TenantLocator = v
}

// GetQuoteLocator returns the QuoteLocator field value
func (o *QuotePriceResponse) GetQuoteLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteLocator
}

// GetQuoteLocatorOk returns a tuple with the QuoteLocator field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetQuoteLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteLocator, true
}

// SetQuoteLocator sets field value
func (o *QuotePriceResponse) SetQuoteLocator(v string) {
	o.QuoteLocator = v
}

// GetAccountLocator returns the AccountLocator field value
func (o *QuotePriceResponse) GetAccountLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountLocator
}

// GetAccountLocatorOk returns a tuple with the AccountLocator field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetAccountLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountLocator, true
}

// SetAccountLocator sets field value
func (o *QuotePriceResponse) SetAccountLocator(v string) {
	o.AccountLocator = v
}

// GetQuoteState returns the QuoteState field value
func (o *QuotePriceResponse) GetQuoteState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteState
}

// GetQuoteStateOk returns a tuple with the QuoteState field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetQuoteStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteState, true
}

// SetQuoteState sets field value
func (o *QuotePriceResponse) SetQuoteState(v string) {
	o.QuoteState = v
}

// GetProductName returns the ProductName field value
func (o *QuotePriceResponse) GetProductName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductName, true
}

// SetProductName sets field value
func (o *QuotePriceResponse) SetProductName(v string) {
	o.ProductName = v
}

// GetStartTime returns the StartTime field value
func (o *QuotePriceResponse) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *QuotePriceResponse) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *QuotePriceResponse) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *QuotePriceResponse) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetDuration returns the Duration field value
func (o *QuotePriceResponse) GetDuration() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *QuotePriceResponse) SetDuration(v float32) {
	o.Duration = v
}

// GetDurationBasis returns the DurationBasis field value
func (o *QuotePriceResponse) GetDurationBasis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DurationBasis
}

// GetDurationBasisOk returns a tuple with the DurationBasis field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetDurationBasisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationBasis, true
}

// SetDurationBasis sets field value
func (o *QuotePriceResponse) SetDurationBasis(v string) {
	o.DurationBasis = v
}

// GetItems returns the Items field value
func (o *QuotePriceResponse) GetItems() []Charge {
	if o == nil {
		var ret []Charge
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetItemsOk() ([]Charge, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *QuotePriceResponse) SetItems(v []Charge) {
	o.Items = v
}

// GetQuoteNumber returns the QuoteNumber field value
func (o *QuotePriceResponse) GetQuoteNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteNumber
}

// GetQuoteNumberOk returns a tuple with the QuoteNumber field value
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetQuoteNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteNumber, true
}

// SetQuoteNumber sets field value
func (o *QuotePriceResponse) SetQuoteNumber(v string) {
	o.QuoteNumber = v
}

// GetValidationResult returns the ValidationResult field value if set, zero value otherwise.
func (o *QuotePriceResponse) GetValidationResult() ValidationResult {
	if o == nil || IsNil(o.ValidationResult) {
		var ret ValidationResult
		return ret
	}
	return *o.ValidationResult
}

// GetValidationResultOk returns a tuple with the ValidationResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotePriceResponse) GetValidationResultOk() (*ValidationResult, bool) {
	if o == nil || IsNil(o.ValidationResult) {
		return nil, false
	}
	return o.ValidationResult, true
}

// HasValidationResult returns a boolean if a field has been set.
func (o *QuotePriceResponse) HasValidationResult() bool {
	if o != nil && !IsNil(o.ValidationResult) {
		return true
	}

	return false
}

// SetValidationResult gets a reference to the given ValidationResult and assigns it to the ValidationResult field.
func (o *QuotePriceResponse) SetValidationResult(v ValidationResult) {
	o.ValidationResult = &v
}

func (o QuotePriceResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotePriceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantLocator"] = o.TenantLocator
	toSerialize["quoteLocator"] = o.QuoteLocator
	toSerialize["accountLocator"] = o.AccountLocator
	toSerialize["quoteState"] = o.QuoteState
	toSerialize["productName"] = o.ProductName
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime
	toSerialize["duration"] = o.Duration
	toSerialize["durationBasis"] = o.DurationBasis
	toSerialize["items"] = o.Items
	toSerialize["quoteNumber"] = o.QuoteNumber
	if !IsNil(o.ValidationResult) {
		toSerialize["validationResult"] = o.ValidationResult
	}
	return toSerialize, nil
}

func (o *QuotePriceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantLocator",
		"quoteLocator",
		"accountLocator",
		"quoteState",
		"productName",
		"startTime",
		"endTime",
		"duration",
		"durationBasis",
		"items",
		"quoteNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuotePriceResponse := _QuotePriceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuotePriceResponse)

	if err != nil {
		return err
	}

	*o = QuotePriceResponse(varQuotePriceResponse)

	return err
}

type NullableQuotePriceResponse struct {
	value *QuotePriceResponse
	isSet bool
}

func (v NullableQuotePriceResponse) Get() *QuotePriceResponse {
	return v.value
}

func (v *NullableQuotePriceResponse) Set(val *QuotePriceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotePriceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotePriceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotePriceResponse(val *QuotePriceResponse) *NullableQuotePriceResponse {
	return &NullableQuotePriceResponse{value: val, isSet: true}
}

func (v NullableQuotePriceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotePriceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
