/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyResponse{}

// PolicyResponse struct for PolicyResponse
type PolicyResponse struct {
	Locator                       string                            `json:"locator"`
	AccountLocator                string                            `json:"accountLocator"`
	BranchHeadTransactionLocators []string                          `json:"branchHeadTransactionLocators"`
	IssuedTransactionLocator      string                            `json:"issuedTransactionLocator"`
	ProductName                   string                            `json:"productName"`
	Timezone                      string                            `json:"timezone"`
	Currency                      string                            `json:"currency"`
	DurationBasis                 string                            `json:"durationBasis"`
	CreatedAt                     time.Time                         `json:"createdAt"`
	CreatedBy                     string                            `json:"createdBy"`
	DelinquencyPlanName           *string                           `json:"delinquencyPlanName,omitempty"`
	BillingTrigger                string                            `json:"billingTrigger"`
	AutoRenewalPlanName           *string                           `json:"autoRenewalPlanName,omitempty"`
	StartTime                     time.Time                         `json:"startTime"`
	EndTime                       time.Time                         `json:"endTime"`
	LatestTermLocator             string                            `json:"latestTermLocator"`
	BillingLevel                  string                            `json:"billingLevel"`
	Region                        *string                           `json:"region,omitempty"`
	PolicyNumber                  *string                           `json:"policyNumber,omitempty"`
	LatestSegmentLocator          string                            `json:"latestSegmentLocator"`
	Contacts                      []ContactRoles                    `json:"contacts"`
	Statuses                      []string                          `json:"statuses"`
	InvoiceFeeAmount              *float32                          `json:"invoiceFeeAmount,omitempty"`
	AnonymizedAt                  *time.Time                        `json:"anonymizedAt,omitempty"`
	ValidationResult              *ValidationResult                 `json:"validationResult,omitempty"`
	Static                        map[string]map[string]interface{} `json:"static"`
}

type _PolicyResponse PolicyResponse

// NewPolicyResponse instantiates a new PolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyResponse(locator string, accountLocator string, branchHeadTransactionLocators []string, issuedTransactionLocator string, productName string, timezone string, currency string, durationBasis string, createdAt time.Time, createdBy string, billingTrigger string, startTime time.Time, endTime time.Time, latestTermLocator string, billingLevel string, latestSegmentLocator string, contacts []ContactRoles, statuses []string, static map[string]map[string]interface{}) *PolicyResponse {
	this := PolicyResponse{}
	this.Locator = locator
	this.AccountLocator = accountLocator
	this.BranchHeadTransactionLocators = branchHeadTransactionLocators
	this.IssuedTransactionLocator = issuedTransactionLocator
	this.ProductName = productName
	this.Timezone = timezone
	this.Currency = currency
	this.DurationBasis = durationBasis
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.BillingTrigger = billingTrigger
	this.StartTime = startTime
	this.EndTime = endTime
	this.LatestTermLocator = latestTermLocator
	this.BillingLevel = billingLevel
	this.LatestSegmentLocator = latestSegmentLocator
	this.Contacts = contacts
	this.Statuses = statuses
	this.Static = static
	return &this
}

// NewPolicyResponseWithDefaults instantiates a new PolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyResponseWithDefaults() *PolicyResponse {
	this := PolicyResponse{}
	return &this
}

// GetLocator returns the Locator field value
func (o *PolicyResponse) GetLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locator
}

// GetLocatorOk returns a tuple with the Locator field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locator, true
}

// SetLocator sets field value
func (o *PolicyResponse) SetLocator(v string) {
	o.Locator = v
}

// GetAccountLocator returns the AccountLocator field value
func (o *PolicyResponse) GetAccountLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountLocator
}

// GetAccountLocatorOk returns a tuple with the AccountLocator field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetAccountLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountLocator, true
}

// SetAccountLocator sets field value
func (o *PolicyResponse) SetAccountLocator(v string) {
	o.AccountLocator = v
}

// GetBranchHeadTransactionLocators returns the BranchHeadTransactionLocators field value
func (o *PolicyResponse) GetBranchHeadTransactionLocators() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BranchHeadTransactionLocators
}

// GetBranchHeadTransactionLocatorsOk returns a tuple with the BranchHeadTransactionLocators field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetBranchHeadTransactionLocatorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BranchHeadTransactionLocators, true
}

// SetBranchHeadTransactionLocators sets field value
func (o *PolicyResponse) SetBranchHeadTransactionLocators(v []string) {
	o.BranchHeadTransactionLocators = v
}

// GetIssuedTransactionLocator returns the IssuedTransactionLocator field value
func (o *PolicyResponse) GetIssuedTransactionLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuedTransactionLocator
}

// GetIssuedTransactionLocatorOk returns a tuple with the IssuedTransactionLocator field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetIssuedTransactionLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuedTransactionLocator, true
}

// SetIssuedTransactionLocator sets field value
func (o *PolicyResponse) SetIssuedTransactionLocator(v string) {
	o.IssuedTransactionLocator = v
}

// GetProductName returns the ProductName field value
func (o *PolicyResponse) GetProductName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductName, true
}

// SetProductName sets field value
func (o *PolicyResponse) SetProductName(v string) {
	o.ProductName = v
}

// GetTimezone returns the Timezone field value
func (o *PolicyResponse) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *PolicyResponse) SetTimezone(v string) {
	o.Timezone = v
}

// GetCurrency returns the Currency field value
func (o *PolicyResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PolicyResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetDurationBasis returns the DurationBasis field value
func (o *PolicyResponse) GetDurationBasis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DurationBasis
}

// GetDurationBasisOk returns a tuple with the DurationBasis field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetDurationBasisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationBasis, true
}

// SetDurationBasis sets field value
func (o *PolicyResponse) SetDurationBasis(v string) {
	o.DurationBasis = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PolicyResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PolicyResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *PolicyResponse) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *PolicyResponse) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetDelinquencyPlanName returns the DelinquencyPlanName field value if set, zero value otherwise.
func (o *PolicyResponse) GetDelinquencyPlanName() string {
	if o == nil || IsNil(o.DelinquencyPlanName) {
		var ret string
		return ret
	}
	return *o.DelinquencyPlanName
}

// GetDelinquencyPlanNameOk returns a tuple with the DelinquencyPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetDelinquencyPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.DelinquencyPlanName) {
		return nil, false
	}
	return o.DelinquencyPlanName, true
}

// HasDelinquencyPlanName returns a boolean if a field has been set.
func (o *PolicyResponse) HasDelinquencyPlanName() bool {
	if o != nil && !IsNil(o.DelinquencyPlanName) {
		return true
	}

	return false
}

// SetDelinquencyPlanName gets a reference to the given string and assigns it to the DelinquencyPlanName field.
func (o *PolicyResponse) SetDelinquencyPlanName(v string) {
	o.DelinquencyPlanName = &v
}

// GetBillingTrigger returns the BillingTrigger field value
func (o *PolicyResponse) GetBillingTrigger() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingTrigger
}

// GetBillingTriggerOk returns a tuple with the BillingTrigger field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetBillingTriggerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingTrigger, true
}

// SetBillingTrigger sets field value
func (o *PolicyResponse) SetBillingTrigger(v string) {
	o.BillingTrigger = v
}

// GetAutoRenewalPlanName returns the AutoRenewalPlanName field value if set, zero value otherwise.
func (o *PolicyResponse) GetAutoRenewalPlanName() string {
	if o == nil || IsNil(o.AutoRenewalPlanName) {
		var ret string
		return ret
	}
	return *o.AutoRenewalPlanName
}

// GetAutoRenewalPlanNameOk returns a tuple with the AutoRenewalPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetAutoRenewalPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.AutoRenewalPlanName) {
		return nil, false
	}
	return o.AutoRenewalPlanName, true
}

// HasAutoRenewalPlanName returns a boolean if a field has been set.
func (o *PolicyResponse) HasAutoRenewalPlanName() bool {
	if o != nil && !IsNil(o.AutoRenewalPlanName) {
		return true
	}

	return false
}

// SetAutoRenewalPlanName gets a reference to the given string and assigns it to the AutoRenewalPlanName field.
func (o *PolicyResponse) SetAutoRenewalPlanName(v string) {
	o.AutoRenewalPlanName = &v
}

// GetStartTime returns the StartTime field value
func (o *PolicyResponse) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *PolicyResponse) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *PolicyResponse) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *PolicyResponse) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetLatestTermLocator returns the LatestTermLocator field value
func (o *PolicyResponse) GetLatestTermLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestTermLocator
}

// GetLatestTermLocatorOk returns a tuple with the LatestTermLocator field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetLatestTermLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestTermLocator, true
}

// SetLatestTermLocator sets field value
func (o *PolicyResponse) SetLatestTermLocator(v string) {
	o.LatestTermLocator = v
}

// GetBillingLevel returns the BillingLevel field value
func (o *PolicyResponse) GetBillingLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingLevel
}

// GetBillingLevelOk returns a tuple with the BillingLevel field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetBillingLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingLevel, true
}

// SetBillingLevel sets field value
func (o *PolicyResponse) SetBillingLevel(v string) {
	o.BillingLevel = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *PolicyResponse) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *PolicyResponse) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *PolicyResponse) SetRegion(v string) {
	o.Region = &v
}

// GetPolicyNumber returns the PolicyNumber field value if set, zero value otherwise.
func (o *PolicyResponse) GetPolicyNumber() string {
	if o == nil || IsNil(o.PolicyNumber) {
		var ret string
		return ret
	}
	return *o.PolicyNumber
}

// GetPolicyNumberOk returns a tuple with the PolicyNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetPolicyNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyNumber) {
		return nil, false
	}
	return o.PolicyNumber, true
}

// HasPolicyNumber returns a boolean if a field has been set.
func (o *PolicyResponse) HasPolicyNumber() bool {
	if o != nil && !IsNil(o.PolicyNumber) {
		return true
	}

	return false
}

// SetPolicyNumber gets a reference to the given string and assigns it to the PolicyNumber field.
func (o *PolicyResponse) SetPolicyNumber(v string) {
	o.PolicyNumber = &v
}

// GetLatestSegmentLocator returns the LatestSegmentLocator field value
func (o *PolicyResponse) GetLatestSegmentLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestSegmentLocator
}

// GetLatestSegmentLocatorOk returns a tuple with the LatestSegmentLocator field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetLatestSegmentLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestSegmentLocator, true
}

// SetLatestSegmentLocator sets field value
func (o *PolicyResponse) SetLatestSegmentLocator(v string) {
	o.LatestSegmentLocator = v
}

// GetContacts returns the Contacts field value
func (o *PolicyResponse) GetContacts() []ContactRoles {
	if o == nil {
		var ret []ContactRoles
		return ret
	}

	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetContactsOk() ([]ContactRoles, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contacts, true
}

// SetContacts sets field value
func (o *PolicyResponse) SetContacts(v []ContactRoles) {
	o.Contacts = v
}

// GetStatuses returns the Statuses field value
func (o *PolicyResponse) GetStatuses() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Statuses
}

// GetStatusesOk returns a tuple with the Statuses field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetStatusesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statuses, true
}

// SetStatuses sets field value
func (o *PolicyResponse) SetStatuses(v []string) {
	o.Statuses = v
}

// GetInvoiceFeeAmount returns the InvoiceFeeAmount field value if set, zero value otherwise.
func (o *PolicyResponse) GetInvoiceFeeAmount() float32 {
	if o == nil || IsNil(o.InvoiceFeeAmount) {
		var ret float32
		return ret
	}
	return *o.InvoiceFeeAmount
}

// GetInvoiceFeeAmountOk returns a tuple with the InvoiceFeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetInvoiceFeeAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.InvoiceFeeAmount) {
		return nil, false
	}
	return o.InvoiceFeeAmount, true
}

// HasInvoiceFeeAmount returns a boolean if a field has been set.
func (o *PolicyResponse) HasInvoiceFeeAmount() bool {
	if o != nil && !IsNil(o.InvoiceFeeAmount) {
		return true
	}

	return false
}

// SetInvoiceFeeAmount gets a reference to the given float32 and assigns it to the InvoiceFeeAmount field.
func (o *PolicyResponse) SetInvoiceFeeAmount(v float32) {
	o.InvoiceFeeAmount = &v
}

// GetAnonymizedAt returns the AnonymizedAt field value if set, zero value otherwise.
func (o *PolicyResponse) GetAnonymizedAt() time.Time {
	if o == nil || IsNil(o.AnonymizedAt) {
		var ret time.Time
		return ret
	}
	return *o.AnonymizedAt
}

// GetAnonymizedAtOk returns a tuple with the AnonymizedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetAnonymizedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AnonymizedAt) {
		return nil, false
	}
	return o.AnonymizedAt, true
}

// HasAnonymizedAt returns a boolean if a field has been set.
func (o *PolicyResponse) HasAnonymizedAt() bool {
	if o != nil && !IsNil(o.AnonymizedAt) {
		return true
	}

	return false
}

// SetAnonymizedAt gets a reference to the given time.Time and assigns it to the AnonymizedAt field.
func (o *PolicyResponse) SetAnonymizedAt(v time.Time) {
	o.AnonymizedAt = &v
}

// GetValidationResult returns the ValidationResult field value if set, zero value otherwise.
func (o *PolicyResponse) GetValidationResult() ValidationResult {
	if o == nil || IsNil(o.ValidationResult) {
		var ret ValidationResult
		return ret
	}
	return *o.ValidationResult
}

// GetValidationResultOk returns a tuple with the ValidationResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetValidationResultOk() (*ValidationResult, bool) {
	if o == nil || IsNil(o.ValidationResult) {
		return nil, false
	}
	return o.ValidationResult, true
}

// HasValidationResult returns a boolean if a field has been set.
func (o *PolicyResponse) HasValidationResult() bool {
	if o != nil && !IsNil(o.ValidationResult) {
		return true
	}

	return false
}

// SetValidationResult gets a reference to the given ValidationResult and assigns it to the ValidationResult field.
func (o *PolicyResponse) SetValidationResult(v ValidationResult) {
	o.ValidationResult = &v
}

// GetStatic returns the Static field value
func (o *PolicyResponse) GetStatic() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Static
}

// GetStaticOk returns a tuple with the Static field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetStaticOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.Static, true
}

// SetStatic sets field value
func (o *PolicyResponse) SetStatic(v map[string]map[string]interface{}) {
	o.Static = v
}

func (o PolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locator"] = o.Locator
	toSerialize["accountLocator"] = o.AccountLocator
	toSerialize["branchHeadTransactionLocators"] = o.BranchHeadTransactionLocators
	toSerialize["issuedTransactionLocator"] = o.IssuedTransactionLocator
	toSerialize["productName"] = o.ProductName
	toSerialize["timezone"] = o.Timezone
	toSerialize["currency"] = o.Currency
	toSerialize["durationBasis"] = o.DurationBasis
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["createdBy"] = o.CreatedBy
	if !IsNil(o.DelinquencyPlanName) {
		toSerialize["delinquencyPlanName"] = o.DelinquencyPlanName
	}
	toSerialize["billingTrigger"] = o.BillingTrigger
	if !IsNil(o.AutoRenewalPlanName) {
		toSerialize["autoRenewalPlanName"] = o.AutoRenewalPlanName
	}
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime
	toSerialize["latestTermLocator"] = o.LatestTermLocator
	toSerialize["billingLevel"] = o.BillingLevel
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.PolicyNumber) {
		toSerialize["policyNumber"] = o.PolicyNumber
	}
	toSerialize["latestSegmentLocator"] = o.LatestSegmentLocator
	toSerialize["contacts"] = o.Contacts
	toSerialize["statuses"] = o.Statuses
	if !IsNil(o.InvoiceFeeAmount) {
		toSerialize["invoiceFeeAmount"] = o.InvoiceFeeAmount
	}
	if !IsNil(o.AnonymizedAt) {
		toSerialize["anonymizedAt"] = o.AnonymizedAt
	}
	if !IsNil(o.ValidationResult) {
		toSerialize["validationResult"] = o.ValidationResult
	}
	toSerialize["static"] = o.Static
	return toSerialize, nil
}

func (o *PolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locator",
		"accountLocator",
		"branchHeadTransactionLocators",
		"issuedTransactionLocator",
		"productName",
		"timezone",
		"currency",
		"durationBasis",
		"createdAt",
		"createdBy",
		"billingTrigger",
		"startTime",
		"endTime",
		"latestTermLocator",
		"billingLevel",
		"latestSegmentLocator",
		"contacts",
		"statuses",
		"static",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyResponse := _PolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyResponse)

	if err != nil {
		return err
	}

	*o = PolicyResponse(varPolicyResponse)

	return err
}

type NullablePolicyResponse struct {
	value *PolicyResponse
	isSet bool
}

func (v NullablePolicyResponse) Get() *PolicyResponse {
	return v.value
}

func (v *NullablePolicyResponse) Set(val *PolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyResponse(val *PolicyResponse) *NullablePolicyResponse {
	return &NullablePolicyResponse{value: val, isSet: true}
}

func (v NullablePolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
