/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListPageResponsePolicyStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPageResponsePolicyStatus{}

// ListPageResponsePolicyStatus struct for ListPageResponsePolicyStatus
type ListPageResponsePolicyStatus struct {
	ListCompleted bool     `json:"listCompleted"`
	Items         []string `json:"items"`
}

type _ListPageResponsePolicyStatus ListPageResponsePolicyStatus

// NewListPageResponsePolicyStatus instantiates a new ListPageResponsePolicyStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPageResponsePolicyStatus(listCompleted bool, items []string) *ListPageResponsePolicyStatus {
	this := ListPageResponsePolicyStatus{}
	this.ListCompleted = listCompleted
	this.Items = items
	return &this
}

// NewListPageResponsePolicyStatusWithDefaults instantiates a new ListPageResponsePolicyStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPageResponsePolicyStatusWithDefaults() *ListPageResponsePolicyStatus {
	this := ListPageResponsePolicyStatus{}
	return &this
}

// GetListCompleted returns the ListCompleted field value
func (o *ListPageResponsePolicyStatus) GetListCompleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ListCompleted
}

// GetListCompletedOk returns a tuple with the ListCompleted field value
// and a boolean to check if the value has been set.
func (o *ListPageResponsePolicyStatus) GetListCompletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListCompleted, true
}

// SetListCompleted sets field value
func (o *ListPageResponsePolicyStatus) SetListCompleted(v bool) {
	o.ListCompleted = v
}

// GetItems returns the Items field value
func (o *ListPageResponsePolicyStatus) GetItems() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListPageResponsePolicyStatus) GetItemsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListPageResponsePolicyStatus) SetItems(v []string) {
	o.Items = v
}

func (o ListPageResponsePolicyStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPageResponsePolicyStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["listCompleted"] = o.ListCompleted
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ListPageResponsePolicyStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listCompleted",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPageResponsePolicyStatus := _ListPageResponsePolicyStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPageResponsePolicyStatus)

	if err != nil {
		return err
	}

	*o = ListPageResponsePolicyStatus(varListPageResponsePolicyStatus)

	return err
}

type NullableListPageResponsePolicyStatus struct {
	value *ListPageResponsePolicyStatus
	isSet bool
}

func (v NullableListPageResponsePolicyStatus) Get() *ListPageResponsePolicyStatus {
	return v.value
}

func (v *NullableListPageResponsePolicyStatus) Set(val *ListPageResponsePolicyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableListPageResponsePolicyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableListPageResponsePolicyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPageResponsePolicyStatus(val *ListPageResponsePolicyStatus) *NullableListPageResponsePolicyStatus {
	return &NullableListPageResponsePolicyStatus{value: val, isSet: true}
}

func (v NullableListPageResponsePolicyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPageResponsePolicyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
