/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuoteUnderwritingFlagsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteUnderwritingFlagsResponse{}

// QuoteUnderwritingFlagsResponse struct for QuoteUnderwritingFlagsResponse
type QuoteUnderwritingFlagsResponse struct {
	QuoteLocator string                     `json:"quoteLocator"`
	Flags        []UnderwritingFlagResponse `json:"flags"`
	ClearedFlags []UnderwritingFlagResponse `json:"clearedFlags"`
}

type _QuoteUnderwritingFlagsResponse QuoteUnderwritingFlagsResponse

// NewQuoteUnderwritingFlagsResponse instantiates a new QuoteUnderwritingFlagsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteUnderwritingFlagsResponse(quoteLocator string, flags []UnderwritingFlagResponse, clearedFlags []UnderwritingFlagResponse) *QuoteUnderwritingFlagsResponse {
	this := QuoteUnderwritingFlagsResponse{}
	this.QuoteLocator = quoteLocator
	this.Flags = flags
	this.ClearedFlags = clearedFlags
	return &this
}

// NewQuoteUnderwritingFlagsResponseWithDefaults instantiates a new QuoteUnderwritingFlagsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteUnderwritingFlagsResponseWithDefaults() *QuoteUnderwritingFlagsResponse {
	this := QuoteUnderwritingFlagsResponse{}
	return &this
}

// GetQuoteLocator returns the QuoteLocator field value
func (o *QuoteUnderwritingFlagsResponse) GetQuoteLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteLocator
}

// GetQuoteLocatorOk returns a tuple with the QuoteLocator field value
// and a boolean to check if the value has been set.
func (o *QuoteUnderwritingFlagsResponse) GetQuoteLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteLocator, true
}

// SetQuoteLocator sets field value
func (o *QuoteUnderwritingFlagsResponse) SetQuoteLocator(v string) {
	o.QuoteLocator = v
}

// GetFlags returns the Flags field value
func (o *QuoteUnderwritingFlagsResponse) GetFlags() []UnderwritingFlagResponse {
	if o == nil {
		var ret []UnderwritingFlagResponse
		return ret
	}

	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value
// and a boolean to check if the value has been set.
func (o *QuoteUnderwritingFlagsResponse) GetFlagsOk() ([]UnderwritingFlagResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Flags, true
}

// SetFlags sets field value
func (o *QuoteUnderwritingFlagsResponse) SetFlags(v []UnderwritingFlagResponse) {
	o.Flags = v
}

// GetClearedFlags returns the ClearedFlags field value
func (o *QuoteUnderwritingFlagsResponse) GetClearedFlags() []UnderwritingFlagResponse {
	if o == nil {
		var ret []UnderwritingFlagResponse
		return ret
	}

	return o.ClearedFlags
}

// GetClearedFlagsOk returns a tuple with the ClearedFlags field value
// and a boolean to check if the value has been set.
func (o *QuoteUnderwritingFlagsResponse) GetClearedFlagsOk() ([]UnderwritingFlagResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClearedFlags, true
}

// SetClearedFlags sets field value
func (o *QuoteUnderwritingFlagsResponse) SetClearedFlags(v []UnderwritingFlagResponse) {
	o.ClearedFlags = v
}

func (o QuoteUnderwritingFlagsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteUnderwritingFlagsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteLocator"] = o.QuoteLocator
	toSerialize["flags"] = o.Flags
	toSerialize["clearedFlags"] = o.ClearedFlags
	return toSerialize, nil
}

func (o *QuoteUnderwritingFlagsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quoteLocator",
		"flags",
		"clearedFlags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteUnderwritingFlagsResponse := _QuoteUnderwritingFlagsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteUnderwritingFlagsResponse)

	if err != nil {
		return err
	}

	*o = QuoteUnderwritingFlagsResponse(varQuoteUnderwritingFlagsResponse)

	return err
}

type NullableQuoteUnderwritingFlagsResponse struct {
	value *QuoteUnderwritingFlagsResponse
	isSet bool
}

func (v NullableQuoteUnderwritingFlagsResponse) Get() *QuoteUnderwritingFlagsResponse {
	return v.value
}

func (v *NullableQuoteUnderwritingFlagsResponse) Set(val *QuoteUnderwritingFlagsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteUnderwritingFlagsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteUnderwritingFlagsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteUnderwritingFlagsResponse(val *QuoteUnderwritingFlagsResponse) *NullableQuoteUnderwritingFlagsResponse {
	return &NullableQuoteUnderwritingFlagsResponse{value: val, isSet: true}
}

func (v NullableQuoteUnderwritingFlagsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteUnderwritingFlagsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
