/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TermPayableResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TermPayableResponse{}

// TermPayableResponse struct for TermPayableResponse
type TermPayableResponse struct {
	Locator       string    `json:"locator"`
	StaticLocator string    `json:"staticLocator"`
	PolicyLocator string    `json:"policyLocator"`
	Number        int32     `json:"number"`
	StartTime     time.Time `json:"startTime"`
	EndTime       time.Time `json:"endTime"`
	Amount        float32   `json:"amount"`
}

type _TermPayableResponse TermPayableResponse

// NewTermPayableResponse instantiates a new TermPayableResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTermPayableResponse(locator string, staticLocator string, policyLocator string, number int32, startTime time.Time, endTime time.Time, amount float32) *TermPayableResponse {
	this := TermPayableResponse{}
	this.Locator = locator
	this.StaticLocator = staticLocator
	this.PolicyLocator = policyLocator
	this.Number = number
	this.StartTime = startTime
	this.EndTime = endTime
	this.Amount = amount
	return &this
}

// NewTermPayableResponseWithDefaults instantiates a new TermPayableResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTermPayableResponseWithDefaults() *TermPayableResponse {
	this := TermPayableResponse{}
	return &this
}

// GetLocator returns the Locator field value
func (o *TermPayableResponse) GetLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locator
}

// GetLocatorOk returns a tuple with the Locator field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locator, true
}

// SetLocator sets field value
func (o *TermPayableResponse) SetLocator(v string) {
	o.Locator = v
}

// GetStaticLocator returns the StaticLocator field value
func (o *TermPayableResponse) GetStaticLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StaticLocator
}

// GetStaticLocatorOk returns a tuple with the StaticLocator field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetStaticLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaticLocator, true
}

// SetStaticLocator sets field value
func (o *TermPayableResponse) SetStaticLocator(v string) {
	o.StaticLocator = v
}

// GetPolicyLocator returns the PolicyLocator field value
func (o *TermPayableResponse) GetPolicyLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyLocator
}

// GetPolicyLocatorOk returns a tuple with the PolicyLocator field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetPolicyLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyLocator, true
}

// SetPolicyLocator sets field value
func (o *TermPayableResponse) SetPolicyLocator(v string) {
	o.PolicyLocator = v
}

// GetNumber returns the Number field value
func (o *TermPayableResponse) GetNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *TermPayableResponse) SetNumber(v int32) {
	o.Number = v
}

// GetStartTime returns the StartTime field value
func (o *TermPayableResponse) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *TermPayableResponse) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *TermPayableResponse) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *TermPayableResponse) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetAmount returns the Amount field value
func (o *TermPayableResponse) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TermPayableResponse) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TermPayableResponse) SetAmount(v float32) {
	o.Amount = v
}

func (o TermPayableResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TermPayableResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locator"] = o.Locator
	toSerialize["staticLocator"] = o.StaticLocator
	toSerialize["policyLocator"] = o.PolicyLocator
	toSerialize["number"] = o.Number
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *TermPayableResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locator",
		"staticLocator",
		"policyLocator",
		"number",
		"startTime",
		"endTime",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTermPayableResponse := _TermPayableResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTermPayableResponse)

	if err != nil {
		return err
	}

	*o = TermPayableResponse(varTermPayableResponse)

	return err
}

type NullableTermPayableResponse struct {
	value *TermPayableResponse
	isSet bool
}

func (v NullableTermPayableResponse) Get() *TermPayableResponse {
	return v.value
}

func (v *NullableTermPayableResponse) Set(val *TermPayableResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTermPayableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTermPayableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTermPayableResponse(val *TermPayableResponse) *NullableTermPayableResponse {
	return &NullableTermPayableResponse{value: val, isSet: true}
}

func (v NullableTermPayableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTermPayableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
