/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountResponse{}

// AccountResponse struct for AccountResponse
type AccountResponse struct {
	Locator                    string                            `json:"locator"`
	Type                       string                            `json:"type"`
	AccountState               string                            `json:"accountState"`
	Data                       map[string]map[string]interface{} `json:"data"`
	DelinquencyPlanName        *string                           `json:"delinquencyPlanName,omitempty"`
	ShortfallTolerancePlanName *string                           `json:"shortfallTolerancePlanName,omitempty"`
	AutoRenewalPlanName        *string                           `json:"autoRenewalPlanName,omitempty"`
	ExcessCreditPlanName       *string                           `json:"excessCreditPlanName,omitempty"`
	Preferences                *Preferences                      `json:"preferences,omitempty"`
	ValidationResult           *ValidationResult                 `json:"validationResult,omitempty"`
	BillingLevel               string                            `json:"billingLevel"`
	InvoicingPlanName          *string                           `json:"invoicingPlanName,omitempty"`
	Region                     *string                           `json:"region,omitempty"`
	InvoiceDocument            *string                           `json:"invoiceDocument,omitempty"`
	Timezone                   *string                           `json:"timezone,omitempty"`
	AccountNumber              string                            `json:"accountNumber"`
	Contacts                   []ContactRoles                    `json:"contacts"`
	// Deprecated
	State string `json:"state"`
}

type _AccountResponse AccountResponse

// NewAccountResponse instantiates a new AccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResponse(locator string, type_ string, accountState string, data map[string]map[string]interface{}, billingLevel string, accountNumber string, contacts []ContactRoles, state string) *AccountResponse {
	this := AccountResponse{}
	this.Locator = locator
	this.Type = type_
	this.AccountState = accountState
	this.Data = data
	this.BillingLevel = billingLevel
	this.AccountNumber = accountNumber
	this.Contacts = contacts
	this.State = state
	return &this
}

// NewAccountResponseWithDefaults instantiates a new AccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResponseWithDefaults() *AccountResponse {
	this := AccountResponse{}
	return &this
}

// GetLocator returns the Locator field value
func (o *AccountResponse) GetLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locator
}

// GetLocatorOk returns a tuple with the Locator field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locator, true
}

// SetLocator sets field value
func (o *AccountResponse) SetLocator(v string) {
	o.Locator = v
}

// GetType returns the Type field value
func (o *AccountResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccountResponse) SetType(v string) {
	o.Type = v
}

// GetAccountState returns the AccountState field value
func (o *AccountResponse) GetAccountState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountState
}

// GetAccountStateOk returns a tuple with the AccountState field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetAccountStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountState, true
}

// SetAccountState sets field value
func (o *AccountResponse) SetAccountState(v string) {
	o.AccountState = v
}

// GetData returns the Data field value
func (o *AccountResponse) GetData() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetDataOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AccountResponse) SetData(v map[string]map[string]interface{}) {
	o.Data = v
}

// GetDelinquencyPlanName returns the DelinquencyPlanName field value if set, zero value otherwise.
func (o *AccountResponse) GetDelinquencyPlanName() string {
	if o == nil || IsNil(o.DelinquencyPlanName) {
		var ret string
		return ret
	}
	return *o.DelinquencyPlanName
}

// GetDelinquencyPlanNameOk returns a tuple with the DelinquencyPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetDelinquencyPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.DelinquencyPlanName) {
		return nil, false
	}
	return o.DelinquencyPlanName, true
}

// HasDelinquencyPlanName returns a boolean if a field has been set.
func (o *AccountResponse) HasDelinquencyPlanName() bool {
	if o != nil && !IsNil(o.DelinquencyPlanName) {
		return true
	}

	return false
}

// SetDelinquencyPlanName gets a reference to the given string and assigns it to the DelinquencyPlanName field.
func (o *AccountResponse) SetDelinquencyPlanName(v string) {
	o.DelinquencyPlanName = &v
}

// GetShortfallTolerancePlanName returns the ShortfallTolerancePlanName field value if set, zero value otherwise.
func (o *AccountResponse) GetShortfallTolerancePlanName() string {
	if o == nil || IsNil(o.ShortfallTolerancePlanName) {
		var ret string
		return ret
	}
	return *o.ShortfallTolerancePlanName
}

// GetShortfallTolerancePlanNameOk returns a tuple with the ShortfallTolerancePlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetShortfallTolerancePlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortfallTolerancePlanName) {
		return nil, false
	}
	return o.ShortfallTolerancePlanName, true
}

// HasShortfallTolerancePlanName returns a boolean if a field has been set.
func (o *AccountResponse) HasShortfallTolerancePlanName() bool {
	if o != nil && !IsNil(o.ShortfallTolerancePlanName) {
		return true
	}

	return false
}

// SetShortfallTolerancePlanName gets a reference to the given string and assigns it to the ShortfallTolerancePlanName field.
func (o *AccountResponse) SetShortfallTolerancePlanName(v string) {
	o.ShortfallTolerancePlanName = &v
}

// GetAutoRenewalPlanName returns the AutoRenewalPlanName field value if set, zero value otherwise.
func (o *AccountResponse) GetAutoRenewalPlanName() string {
	if o == nil || IsNil(o.AutoRenewalPlanName) {
		var ret string
		return ret
	}
	return *o.AutoRenewalPlanName
}

// GetAutoRenewalPlanNameOk returns a tuple with the AutoRenewalPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetAutoRenewalPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.AutoRenewalPlanName) {
		return nil, false
	}
	return o.AutoRenewalPlanName, true
}

// HasAutoRenewalPlanName returns a boolean if a field has been set.
func (o *AccountResponse) HasAutoRenewalPlanName() bool {
	if o != nil && !IsNil(o.AutoRenewalPlanName) {
		return true
	}

	return false
}

// SetAutoRenewalPlanName gets a reference to the given string and assigns it to the AutoRenewalPlanName field.
func (o *AccountResponse) SetAutoRenewalPlanName(v string) {
	o.AutoRenewalPlanName = &v
}

// GetExcessCreditPlanName returns the ExcessCreditPlanName field value if set, zero value otherwise.
func (o *AccountResponse) GetExcessCreditPlanName() string {
	if o == nil || IsNil(o.ExcessCreditPlanName) {
		var ret string
		return ret
	}
	return *o.ExcessCreditPlanName
}

// GetExcessCreditPlanNameOk returns a tuple with the ExcessCreditPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetExcessCreditPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.ExcessCreditPlanName) {
		return nil, false
	}
	return o.ExcessCreditPlanName, true
}

// HasExcessCreditPlanName returns a boolean if a field has been set.
func (o *AccountResponse) HasExcessCreditPlanName() bool {
	if o != nil && !IsNil(o.ExcessCreditPlanName) {
		return true
	}

	return false
}

// SetExcessCreditPlanName gets a reference to the given string and assigns it to the ExcessCreditPlanName field.
func (o *AccountResponse) SetExcessCreditPlanName(v string) {
	o.ExcessCreditPlanName = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *AccountResponse) GetPreferences() Preferences {
	if o == nil || IsNil(o.Preferences) {
		var ret Preferences
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetPreferencesOk() (*Preferences, bool) {
	if o == nil || IsNil(o.Preferences) {
		return nil, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *AccountResponse) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given Preferences and assigns it to the Preferences field.
func (o *AccountResponse) SetPreferences(v Preferences) {
	o.Preferences = &v
}

// GetValidationResult returns the ValidationResult field value if set, zero value otherwise.
func (o *AccountResponse) GetValidationResult() ValidationResult {
	if o == nil || IsNil(o.ValidationResult) {
		var ret ValidationResult
		return ret
	}
	return *o.ValidationResult
}

// GetValidationResultOk returns a tuple with the ValidationResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetValidationResultOk() (*ValidationResult, bool) {
	if o == nil || IsNil(o.ValidationResult) {
		return nil, false
	}
	return o.ValidationResult, true
}

// HasValidationResult returns a boolean if a field has been set.
func (o *AccountResponse) HasValidationResult() bool {
	if o != nil && !IsNil(o.ValidationResult) {
		return true
	}

	return false
}

// SetValidationResult gets a reference to the given ValidationResult and assigns it to the ValidationResult field.
func (o *AccountResponse) SetValidationResult(v ValidationResult) {
	o.ValidationResult = &v
}

// GetBillingLevel returns the BillingLevel field value
func (o *AccountResponse) GetBillingLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingLevel
}

// GetBillingLevelOk returns a tuple with the BillingLevel field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetBillingLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingLevel, true
}

// SetBillingLevel sets field value
func (o *AccountResponse) SetBillingLevel(v string) {
	o.BillingLevel = v
}

// GetInvoicingPlanName returns the InvoicingPlanName field value if set, zero value otherwise.
func (o *AccountResponse) GetInvoicingPlanName() string {
	if o == nil || IsNil(o.InvoicingPlanName) {
		var ret string
		return ret
	}
	return *o.InvoicingPlanName
}

// GetInvoicingPlanNameOk returns a tuple with the InvoicingPlanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetInvoicingPlanNameOk() (*string, bool) {
	if o == nil || IsNil(o.InvoicingPlanName) {
		return nil, false
	}
	return o.InvoicingPlanName, true
}

// HasInvoicingPlanName returns a boolean if a field has been set.
func (o *AccountResponse) HasInvoicingPlanName() bool {
	if o != nil && !IsNil(o.InvoicingPlanName) {
		return true
	}

	return false
}

// SetInvoicingPlanName gets a reference to the given string and assigns it to the InvoicingPlanName field.
func (o *AccountResponse) SetInvoicingPlanName(v string) {
	o.InvoicingPlanName = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AccountResponse) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AccountResponse) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *AccountResponse) SetRegion(v string) {
	o.Region = &v
}

// GetInvoiceDocument returns the InvoiceDocument field value if set, zero value otherwise.
func (o *AccountResponse) GetInvoiceDocument() string {
	if o == nil || IsNil(o.InvoiceDocument) {
		var ret string
		return ret
	}
	return *o.InvoiceDocument
}

// GetInvoiceDocumentOk returns a tuple with the InvoiceDocument field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetInvoiceDocumentOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceDocument) {
		return nil, false
	}
	return o.InvoiceDocument, true
}

// HasInvoiceDocument returns a boolean if a field has been set.
func (o *AccountResponse) HasInvoiceDocument() bool {
	if o != nil && !IsNil(o.InvoiceDocument) {
		return true
	}

	return false
}

// SetInvoiceDocument gets a reference to the given string and assigns it to the InvoiceDocument field.
func (o *AccountResponse) SetInvoiceDocument(v string) {
	o.InvoiceDocument = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *AccountResponse) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *AccountResponse) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *AccountResponse) SetTimezone(v string) {
	o.Timezone = &v
}

// GetAccountNumber returns the AccountNumber field value
func (o *AccountResponse) GetAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountNumber, true
}

// SetAccountNumber sets field value
func (o *AccountResponse) SetAccountNumber(v string) {
	o.AccountNumber = v
}

// GetContacts returns the Contacts field value
func (o *AccountResponse) GetContacts() []ContactRoles {
	if o == nil {
		var ret []ContactRoles
		return ret
	}

	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetContactsOk() ([]ContactRoles, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contacts, true
}

// SetContacts sets field value
func (o *AccountResponse) SetContacts(v []ContactRoles) {
	o.Contacts = v
}

// GetState returns the State field value
// Deprecated
func (o *AccountResponse) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *AccountResponse) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
// Deprecated
func (o *AccountResponse) SetState(v string) {
	o.State = v
}

func (o AccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locator"] = o.Locator
	toSerialize["type"] = o.Type
	toSerialize["accountState"] = o.AccountState
	toSerialize["data"] = o.Data
	if !IsNil(o.DelinquencyPlanName) {
		toSerialize["delinquencyPlanName"] = o.DelinquencyPlanName
	}
	if !IsNil(o.ShortfallTolerancePlanName) {
		toSerialize["shortfallTolerancePlanName"] = o.ShortfallTolerancePlanName
	}
	if !IsNil(o.AutoRenewalPlanName) {
		toSerialize["autoRenewalPlanName"] = o.AutoRenewalPlanName
	}
	if !IsNil(o.ExcessCreditPlanName) {
		toSerialize["excessCreditPlanName"] = o.ExcessCreditPlanName
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	if !IsNil(o.ValidationResult) {
		toSerialize["validationResult"] = o.ValidationResult
	}
	toSerialize["billingLevel"] = o.BillingLevel
	if !IsNil(o.InvoicingPlanName) {
		toSerialize["invoicingPlanName"] = o.InvoicingPlanName
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.InvoiceDocument) {
		toSerialize["invoiceDocument"] = o.InvoiceDocument
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	toSerialize["accountNumber"] = o.AccountNumber
	toSerialize["contacts"] = o.Contacts
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *AccountResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locator",
		"type",
		"accountState",
		"data",
		"billingLevel",
		"accountNumber",
		"contacts",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountResponse := _AccountResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountResponse)

	if err != nil {
		return err
	}

	*o = AccountResponse(varAccountResponse)

	return err
}

type NullableAccountResponse struct {
	value *AccountResponse
	isSet bool
}

func (v NullableAccountResponse) Get() *AccountResponse {
	return v.value
}

func (v *NullableAccountResponse) Set(val *AccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResponse(val *AccountResponse) *NullableAccountResponse {
	return &NullableAccountResponse{value: val, isSet: true}
}

func (v NullableAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
