/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InstallmentEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallmentEvents{}

// InstallmentEvents struct for InstallmentEvents
type InstallmentEvents struct {
	BillingInstallmentlatticeCreate *InstallmentLatticeCreateData `json:"billing.installmentlattice.create,omitempty"`
}

// NewInstallmentEvents instantiates a new InstallmentEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallmentEvents() *InstallmentEvents {
	this := InstallmentEvents{}
	return &this
}

// NewInstallmentEventsWithDefaults instantiates a new InstallmentEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallmentEventsWithDefaults() *InstallmentEvents {
	this := InstallmentEvents{}
	return &this
}

// GetBillingInstallmentlatticeCreate returns the BillingInstallmentlatticeCreate field value if set, zero value otherwise.
func (o *InstallmentEvents) GetBillingInstallmentlatticeCreate() InstallmentLatticeCreateData {
	if o == nil || IsNil(o.BillingInstallmentlatticeCreate) {
		var ret InstallmentLatticeCreateData
		return ret
	}
	return *o.BillingInstallmentlatticeCreate
}

// GetBillingInstallmentlatticeCreateOk returns a tuple with the BillingInstallmentlatticeCreate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallmentEvents) GetBillingInstallmentlatticeCreateOk() (*InstallmentLatticeCreateData, bool) {
	if o == nil || IsNil(o.BillingInstallmentlatticeCreate) {
		return nil, false
	}
	return o.BillingInstallmentlatticeCreate, true
}

// HasBillingInstallmentlatticeCreate returns a boolean if a field has been set.
func (o *InstallmentEvents) HasBillingInstallmentlatticeCreate() bool {
	if o != nil && !IsNil(o.BillingInstallmentlatticeCreate) {
		return true
	}

	return false
}

// SetBillingInstallmentlatticeCreate gets a reference to the given InstallmentLatticeCreateData and assigns it to the BillingInstallmentlatticeCreate field.
func (o *InstallmentEvents) SetBillingInstallmentlatticeCreate(v InstallmentLatticeCreateData) {
	o.BillingInstallmentlatticeCreate = &v
}

func (o InstallmentEvents) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallmentEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingInstallmentlatticeCreate) {
		toSerialize["billing.installmentlattice.create"] = o.BillingInstallmentlatticeCreate
	}
	return toSerialize, nil
}

type NullableInstallmentEvents struct {
	value *InstallmentEvents
	isSet bool
}

func (v NullableInstallmentEvents) Get() *InstallmentEvents {
	return v.value
}

func (v *NullableInstallmentEvents) Set(val *InstallmentEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallmentEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallmentEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallmentEvents(val *InstallmentEvents) *NullableInstallmentEvents {
	return &NullableInstallmentEvents{value: val, isSet: true}
}

func (v NullableInstallmentEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallmentEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
