/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecretRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretRef{}

// SecretRef struct for SecretRef
type SecretRef struct {
	Items map[string]PrimitivePropertyRef `json:"items"`
}

type _SecretRef SecretRef

// NewSecretRef instantiates a new SecretRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretRef(items map[string]PrimitivePropertyRef) *SecretRef {
	this := SecretRef{}
	this.Items = items
	return &this
}

// NewSecretRefWithDefaults instantiates a new SecretRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretRefWithDefaults() *SecretRef {
	this := SecretRef{}
	return &this
}

// GetItems returns the Items field value
func (o *SecretRef) GetItems() map[string]PrimitivePropertyRef {
	if o == nil {
		var ret map[string]PrimitivePropertyRef
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SecretRef) GetItemsOk() (*map[string]PrimitivePropertyRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *SecretRef) SetItems(v map[string]PrimitivePropertyRef) {
	o.Items = v
}

func (o SecretRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *SecretRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretRef := _SecretRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretRef)

	if err != nil {
		return err
	}

	*o = SecretRef(varSecretRef)

	return err
}

type NullableSecretRef struct {
	value *SecretRef
	isSet bool
}

func (v NullableSecretRef) Get() *SecretRef {
	return v.value
}

func (v *NullableSecretRef) Set(val *SecretRef) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretRef) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretRef(val *SecretRef) *NullableSecretRef {
	return &NullableSecretRef{value: val, isSet: true}
}

func (v NullableSecretRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
