/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DataAccessControlFieldRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataAccessControlFieldRef{}

// DataAccessControlFieldRef struct for DataAccessControlFieldRef
type DataAccessControlFieldRef struct {
	Fields []string `json:"fields"`
}

type _DataAccessControlFieldRef DataAccessControlFieldRef

// NewDataAccessControlFieldRef instantiates a new DataAccessControlFieldRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataAccessControlFieldRef(fields []string) *DataAccessControlFieldRef {
	this := DataAccessControlFieldRef{}
	this.Fields = fields
	return &this
}

// NewDataAccessControlFieldRefWithDefaults instantiates a new DataAccessControlFieldRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataAccessControlFieldRefWithDefaults() *DataAccessControlFieldRef {
	this := DataAccessControlFieldRef{}
	return &this
}

// GetFields returns the Fields field value
func (o *DataAccessControlFieldRef) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *DataAccessControlFieldRef) GetFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *DataAccessControlFieldRef) SetFields(v []string) {
	o.Fields = v
}

func (o DataAccessControlFieldRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataAccessControlFieldRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *DataAccessControlFieldRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataAccessControlFieldRef := _DataAccessControlFieldRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataAccessControlFieldRef)

	if err != nil {
		return err
	}

	*o = DataAccessControlFieldRef(varDataAccessControlFieldRef)

	return err
}

type NullableDataAccessControlFieldRef struct {
	value *DataAccessControlFieldRef
	isSet bool
}

func (v NullableDataAccessControlFieldRef) Get() *DataAccessControlFieldRef {
	return v.value
}

func (v *NullableDataAccessControlFieldRef) Set(val *DataAccessControlFieldRef) {
	v.value = val
	v.isSet = true
}

func (v NullableDataAccessControlFieldRef) IsSet() bool {
	return v.isSet
}

func (v *NullableDataAccessControlFieldRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataAccessControlFieldRef(val *DataAccessControlFieldRef) *NullableDataAccessControlFieldRef {
	return &NullableDataAccessControlFieldRef{value: val, isSet: true}
}

func (v NullableDataAccessControlFieldRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataAccessControlFieldRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
